### ISSUE TITLE
Create test data repo

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/sbl-project#116]
Create regtech test data repo as a test suite to aid end to end testing. Will start with mock institutions data.

**Comment by jcadam14** [comment]
@lchen-2101 We now have https://github.com/cfpb/sbl-test-data, do we want to add the json mock data here from dev_setup/mock_data?

**Comment by lchen-2101** [comment]
> @lchen-2101 We now have https://github.com/cfpb/sbl-test-data, do we want to add the json mock data here from dev_setup/mock_data?

sounds good to me
