### ISSUE TITLE
Check Login.gov back to app link upon reaching Login.gov screen

### ISSUE THREAD

**Issue by lchen-2101** [cfpb/sbl-project#129]
When directing back to the front end app upon reaching Login.gov without logging in, the Keycloak login screen is shown; check configurations to correct this.

**Comment by natalia-fitzgerald** [comment]
@lchen-2101 
Is there more work to do on this ticket?

**Comment by lchen-2101** [comment]
no more work needs to be done on this, I'm closing it.
