### ISSUE TITLE
Standardize Python repo structure

### ISSUE THREAD

**Issue by hkeeler** [cfpb/sbl-project#132]
We have several Python-based git repos now. Some with just the top-level module name in the root, some with `src/top-level-module`, and some with `src` without really a top-level module. Let's decide on how we want to standardize these, and refactor the repo structure(s) as needed.

See discussion on https://github.com/cfpb/regtech-mail-api/pull/4#discussion_r1480615642 for more details.

**Comment by jcadam14** [comment]
See the following stories:
https://github.com/cfpb/regtech-mail-api/issues/26
https://github.com/cfpb/sbl-filing-api/issues/120
https://github.com/cfpb/regtech-user-fi-management/issues/123
https://github.com/cfpb/regtech-data-validator/issues/110

**Comment by jcadam14** [comment]
All stories above have been completed
