### ISSUE TITLE
[Story] Provide the appropriate types of financial institutions

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#139]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

[Epic] Provide type of financial institution https://github.com/cfpb/sbl-project/issues/143

### User story

As a filer, I want to provide the appropriate type of financial institutions from the list provided, so that I can be in compliance with 12 CFR § 1002.109(b)(9).

### Acceptance criteria

Given [some context or conditions], when [the action that is performed], then [the expected observable outcome or behavior].

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [x] [[Page] Type of Financial Institution - Phase 1 - Skeleton](https://github.com/cfpb/sbl-frontend/issues/284)
- [x] [[Page] Type of Financial Institution - Phase 2 - API Request](https://github.com/cfpb/sbl-frontend/issues/291)
- [x] https://github.com/cfpb/sbl-frontend/issues/455

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
## Decision:
On 1/22/2024 we met as a group to complete our backlog refinement conversation from yesterday. We determined that for MVP we will go with the flow shown in [Approach 2](https://github.com/cfpb/sbl-project/issues/139#issuecomment-1957871479) (above) where a filer that has never provided type of financial institution will see "Provide type of financial institution" as their first task. Once they complete this task they continue to "Step 1: Upload file". 

@dan-padgett @angelcardoz
