### ISSUE TITLE
[Story] Provide business point of contact information for filing

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#147]
#### [Epic: Provide filing details](https://github.com/cfpb/sbl-project/issues/150) 

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

### User story

As a filer, I want to provide the name and business contact information of a person that the CFPB or other regulators may contact about my financial institution's filing, so that I can fulfill the regulatory requirement.

### Acceptance criteria

Given a user has reached the provide filing details step, when they scroll to provide point of contact, then they can provide all required information.

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [x] https://github.com/cfpb/sbl-frontend/issues/287
- [x] https://github.com/cfpb/sbl-frontend/issues/297
- [x] https://github.com/cfpb/sbl-frontend/issues/288
- [x] https://github.com/cfpb/sbl-frontend/issues/393

#### Back end
- [x] https://github.com/cfpb/sbl-filing-api/issues/62

**Comment by natalia-fitzgerald** [comment]
@Kibrael @nongarak 
Let's capture this at the epic level here: https://github.com/cfpb/sbl-project/issues/150#issuecomment-1965033255

I reviewed the HMDA fields and captured them in the mock-up. Please review and let me know if anything is missing. https://github.com/cfpb/sbl-project/issues/150#issue-2154683428

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
Here's a suggested update to this story to more closely mirror the rule language: 
"As a filer, I want to provide the name and business contact information of a person that the Bureau or other regulators may contact about my financial institution's submission, so that I can fulfill the regulatory requirement."

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
Since this was a beta story and we completed it I am closing this story (and will check it off on the epic).
