### ISSUE TITLE
[Story] Review register filing details

### ISSUE THREAD

**Issue by sthomas93** [cfpb/sbl-project#181]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer I want to review my register upload summary, so that I can confirm that my information is correct and proceed with finalizing my filing.

### Acceptance criteria

Given a system user has completed all previous steps, when they land on the sign and submit page the system will display a section with a register upload summary (filing year, file name, uploaded by, uploaded date, total errors, number of verified warnings, and total number of loans/applications), then the user will be able to review the data for accuracy and completeness.

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by angelcardoz** [comment]
Changed "As a filer I want to be able to review my SBLAR details, so that I can confirm the information is correct and proceed to finalizing my filing" to  "As a filer I want to review my register upload summary, so that I can confirm the information is correct and proceed to finalizing my filing."

**Comment by natalia-fitzgerald** [comment]
Tracking in this consolidated story: 
- https://github.com/cfpb/sbl-project/issues/258
