### ISSUE TITLE
[Story] How to change incorrect register filing details

### ISSUE THREAD

**Issue by sthomas93** [cfpb/sbl-project#182]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit ](https://github.com/cfpb/sbl-project/issues/180) 

### User story

-  As a filer, I want to know how  to change any incorrect register information I find in my review, so that I can update my point of contact.

### Acceptance criteria

- Given a system user is in the sign and submit page, when they scroll down to the register upload summary section the system will display information on how to make changes to their uploaded register if they find the information is inaccurate or incomplete, then they will be able to follow the instructions to make the changes.

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by angelcardoz** [comment]
Changed from "As a filer I want to to be able to change any incorrect information I find in my filing review so that I can update my details with the correct information." to " As a filer, I want to know how  to change any incorrect register information I find in my review, so that I can update my point of contact."

**Comment by natalia-fitzgerald** [comment]
Tracking moved to this consolidated issue: 
- https://github.com/cfpb/sbl-project/issues/259
