### ISSUE TITLE
[Story] Review financial institution details

### ISSUE THREAD

**Issue by sthomas93** [cfpb/sbl-project#188]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, I want to review my financial institution details, so that I can confirm that my information is correct and proceed with finalizing my filing.

### Acceptance criteria

- Given a system user has completed all previous steps, when they land on the sign and submit page the system will display a section with financial institution details (financial institution name, headquarter address, Legal Entity Identifier, and LEI Status), then the user will be able to review the data for accuracy and completeness. 

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
Tracking in this consolidated story: 
- https://github.com/cfpb/sbl-project/issues/258
