### ISSUE TITLE
Update usability testing plan

### ISSUE THREAD

**Issue by dan-padgett** [cfpb/sbl-project#196]
Based on the results of the practice run, update the usability testing plan. This includes:
- [x] Updating prototype content
- [x] Fixing "on click" issue with the prototype
- [x] Ensuring all checkboxes have intended functionality
- [x] Deciding and implementing any updates to the study in UserZoom
- [x] Writing additional instructions to send to participants
- [x] Revising test task language

**Comment by natalia-fitzgerald** [comment]
@angelcardoz - I confirmed with @dan-padgett that this can be closed. Closing now...
