### ISSUE TITLE
Add message to "Your email domain is not authorized" page to contact support staff if their issue persists

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/sbl-project#208]
Per pre-clearance feedback, we should add a sentence to the "Your email domain is not authorized" page to contact our support staff if their issue persists.

**Comment by natalia-fitzgerald** [comment]
@chynnakeys @angelcardoz 
We made this addition before beta launch. Is there any remaining work or tracking to do on this ticket? 
<img width="815" alt="Screenshot 2024-10-07 at 11 51 35 AM" src="https://github.com/user-attachments/assets/761d4d59-7ef9-4075-ab26-7450423e669d">
