### ISSUE TITLE
Add message to "Complete your user profile" page to contact support staff if users have any issues

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/sbl-project#209]
Add message to "Complete your user profile" page to contact support staff if users have any issues. This should be added to the body text below the header. See mockup for update.

**Comment by natalia-fitzgerald** [comment]
@chynnakeys @angelcardoz 
Can we close this based on the addition of the last line in the intro content below. This is what we launched with for beta. 
<img width="468" alt="Screenshot 2024-10-07 at 11 48 53 AM" src="https://github.com/user-attachments/assets/db5182f5-fa6e-443e-9031-348f9e94320c">
