### ISSUE TITLE
UX Research and Design Questions

### ISSUE THREAD

**Issue by dan-padgett** [cfpb/sbl-project#215]
Along with all of the design and research questions we've addressed through the focus group and usability testing, there are a number of open questions that we need to capture and prioritize for post-launch research. These questions will be categorized under the following themes:
- Creating/Completing your user profile
- Filing for your institution
- Getting help
- Global design questions

To capture these questions, we'll look at:
- [x] Figma
- [x] Mural (Task Analysis)
- [x] Focus Group report
- [x] Usability testing results
- [x] Task ideation for epics
- [x] Pre-clearance comments

**Comment by dan-padgett** [comment]
# Creating/Completing your user profile

**Comment by dan-padgett** [comment]
# Filing for your institution

**Comment by dan-padgett** [comment]
# Getting help

**Comment by dan-padgett** [comment]
@angelcardoz @natalia-fitzgerald I've completed my review for where our open research and design questions are. Can you take a look at this list and let me know what I've missed or what needs to be re-phrased?

**Comment by angelcardoz** [comment]
Thanks for working on these @dan-padgett. Please consider the following in addition to outstanding pre-clearance questions:

**Shared Platform**

This is a big one, which will require conversations with outside stakeholders, but should we consider merging "Shared platform (authenticated)" and "filing home", at least until we decide HMDA will be joining the shared platform?

**Financial Institution Details**

We removed a section that that allowed users to provide additional details when requesting an update to their financial institution profile. Is there a need for this free text field? Should we consider adding it back?

**Filing home**

Are secondary link helpful? Is there a secondary link we should add for the provide point of contact and sign and submit your filing? What would users expect?


**Errors and warnings**

Is the downloadable csv information useful? Do they expect more or less information? If so, which columns should we remove and/or add.

Do participants have any reactions to the way the tables are organized? For instance, do they expect different columns or different header names?

 Do participants have any reactions to the way the tables themselves? For instance, how do they react to pagination? Would they prefer a scrollable table?

Are most users simply downloading report as opposed to clicking through the various table pages?

**Point of Contact**

Doe we need to add another optional field with "Business Name" for third party POCs?

**Sign and submit**
 
Say a user is filing last minute, and doesn't have the ability to update their FI3 with GLEIF or NIC in time for filing, but still wants to submit the most up to date information to CFPB, would a user expect to see a way to provide that information to us here? What does that process look like?

**Global design questions.**

Should we add "To provide feedback, email our support staff" to the beta banner that shows up in each page?

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
Additional design questions: 

### View financial institution profile
- Does the "Update your financial institution profile" link have enough prominence? 
- Should the View and Update page be merged into a single page (currently the database values pre-populate on the update page)
