### ISSUE TITLE
[Story] Indicate voluntary reporter status

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#243]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- https://github.com/cfpb/sbl-project/issues/150) 

### User story

- As a user that elects to voluntarily compile, maintain, and report data, I want to indicate that I'm a voluntary reporter, so that I can comply with § 1002.109(b)(10).

### Acceptance criteria

- Given a user reaches the provide filing details step, when they reach the voluntary reporter status section, then they will be able to select their voluntary reporter status.

### Technical tasks

Team members should create technical tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
- [x] Map story issue to the task analysis
- [x] Validate user story
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness
- [x] https://github.com/cfpb/sbl-ux/issues/8
- [x] https://github.com/cfpb/sbl-ux/issues/9

#### Content
- [x] Write section content
- [x] Run by legal for review

#### Front end
- [x] [[Page] Sign & submit - Phase 2 - latest design/content](https://github.com/cfpb/sbl-frontend/issues/476)
- [x] [[Page] [Point of Contact] --> [Provide Filing Details], Integrate backend of Voluntary Reporter Status functionality](https://github.com/cfpb/sbl-frontend/issues/991)

#### Back end
- Add task

#### Data
- Add task

**Comment by natalia-fitzgerald** [comment]
### Design mock-ups 
| Base state | Selected state |
|------------|------------|
|<img width="675" alt="Screenshot 2024-09-30 at 12 10 37 PM" src="https://github.com/user-attachments/assets/0bf2523a-9c56-4688-b79b-9518a5139ab4">|<img width="691" alt="Screenshot 2024-09-30 at 12 11 10 PM" src="https://github.com/user-attachments/assets/aa76ea7f-03f3-4915-ab06-4757885d4caf">|

**Comment by natalia-fitzgerald** [comment]
Here's a screenshot of the implemented feature in beta. 
<img width="1469" alt="Screenshot 2024-12-11 at 11 43 55 AM" src="https://github.com/user-attachments/assets/aadd9829-e4e2-4d1a-b885-8bc68ed4d6fb" />


@angelcardoz 
This story is completed and can be closed.
