### ISSUE TITLE
[Story] Confirm financial institution identifying information is correct

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#247]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, I want a way to confirm that I've reviewed the section displaying my financial institution identifying information and that the data displayed is correct, so that I can ensure the information I'm submitting is accurate and complete.

### Acceptance criteria

- Given a system user has reviewed their financial institution identifying information and the information is correct, when they check the checkbox, then the checkbox will display a visual cue (e.g. checkmark) indicating that the user has reviewed the section and confirmed that the information is correct.

### Tasks

Team should create tasks and add links (below) prior to sprint planning.

#### UX Design / Content
- [ ] Create mock-up for confirm financial institution identifying information
- [ ] Write section content 

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
Tracking this work in this consolidated story: 
- https://github.com/cfpb/sbl-project/issues/260
