### ISSUE TITLE
[Story] How to change incorrect parent entity information

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#249]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- I want to know how to change any incorrect financial institution parent entity information I find in my review, so that I can update my parent entity information.

### Acceptance criteria

-  Given a system user is in the sign and submit page, when they scroll down to the parent entity information section the system will display information on how to make changes to their parent entity information details if they find the information is  inaccurate or incomplete, then they will be able to follow the instructions to make the changes.

### Technical tasks

Developers should create technical tasks and add links (below) prior to sprint planning.

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
Tracking moved to this consolidated issue: 
- https://github.com/cfpb/sbl-project/issues/259
