### ISSUE TITLE
[Story] How to change incorrect voluntary reporter status

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#255]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- [[Epic] Sign and Submit](https://github.com/cfpb/sbl-project/issues/180)

### User story

- As a filer, I want to know how to change an incorrect voluntary reporter status I find in my review, so that I can update my voluntary reporter status.

### Acceptance criteria

- Given a system user is in the sign and submit page, when they scroll down to the voluntary reporter status section the system will display information on how to make changes to their voluntary reporter status if they find the information is inaccurate or incomplete, then they will be able to follow the instructions to make the change.

### Tasks

Team members should create tasks and add links (below) prior to sprint planning.

#### UX Design / Content
- [ ] Confirm where a user must go to change incorrect voluntary reporter status
- [ ] Write content for where a user must go to change incorrect voluntary reporter status

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
Tracking moved to this consolidated issue: 
- https://github.com/cfpb/sbl-project/issues/259
