### ISSUE TITLE
[Story] Provide phone extension for business point of contact

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#265]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- https://github.com/cfpb/sbl-project/issues/150

### User story

- As a filer, I want to have the option to provide the phone extension for the business point of contact for my filing, so that the CFPB or other regulators can more easily make contact.

### Acceptance criteria

- [x] Given the user has reached the provide point of contact step, when they scroll to the point of contact form, then they can provide the phone extension for the business point of contact.
- [x] Given the user has reached the point of contact form, when they go to enter their extension, then they are made aware of the number of digits they can include.
- [x] Given the user has reached the point of contact form,  when they choose not to enter a phone extension, then the system should allow them to continue without requiring an extension.
- [x] Given the user is filling out the phone extension field, when the user inputs a numeric value between 1 and 9 digits, then the fields should accept the value as valid. 

### Technical tasks

Team members should create technical tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
- [x] Map story issue to the task analysis
- [x] Validate user story
  - Review against task analysis for accuracy and relevance
  - Review for specificity and completeness
- [x] Create a [design mock-up](https://github.com/cfpb/sbl-project/issues/265#issuecomment-2380014925) for first set of acceptance criteria (Sprint 41)
- [x] Create a design mock-up for second set of acceptance criteria (scheduled for Sprint 42)
- [x] https://github.com/cfpb/sbl-ux/issues/14

#### Content
- [x] Write content label and helper text for initial set of acceptance criteria
- [x] https://github.com/cfpb/sbl-ux/issues/6
 
#### Front end
- [x] https://github.com/cfpb/sbl-frontend/issues/945
- [x] https://github.com/cfpb/sbl-frontend/pull/976
- [x] https://github.com/cfpb/sbl-frontend/issues/983

#### Back end
- [x] https://github.com/cfpb/sbl-filing-api/issues/420

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
The following reflect the designs we discussed for the phone extension.

### Mock-up details
- Phone number and extension fields appear side-by-side at all screen widths
- Phone number field is 2/3 width 
- Extension field is 1/3 width
- There is a 15px horizontal gap between the two fields 
- The extension field is optional
- Numbers and letters are both acceptable
- The intended purpose of the extension field is to accommodate extension numbers 
- The field should accommodate a reasonable number characters/numbers 
  - We found a recommendation of 11 digits/characters in our research

| Desktop | Mobile |
|------------|------------|
|<img width="449" alt="Screenshot 2024-09-27 at 4 19 13 PM" src="https://github.com/user-attachments/assets/8f9147f7-3d41-4b6e-a233-bb936d636da9">|<img width="334" alt="Screenshot 2024-09-27 at 4 19 05 PM" src="https://github.com/user-attachments/assets/5ab8f6fd-1416-4bab-a2a5-8650b13fd83e">|

**Comment by dan-padgett** [comment]
Thanks @natalia-fitzgerald! Since this is just an addition to phone number, I'll check off the validation task.

**Comment by natalia-fitzgerald** [comment]
The front end has now implemented the [design shown here](https://github.com/cfpb/sbl-project/issues/265#issuecomment-2380014925). The backend and the front end have been set up to accept 254 max characters (letters, numbers, or special characters).

There is a product owner preference to stay as close to the stakeholder request as possible which is to add a field that's strictly for phone extension. There are concerns with accommodating 254 characters as it could lead to unintended consequences. One concern is that we open up the field to inadvertently collecting PII.

I have discussed with development and, in a future sprint, we can prioritize making a change to more tightly define the number of characters (11-15 or some number we define). This change will require backend, frontend, content, and design work. 

@angelcardoz - Do we want to release this within this sprint the way we have it and then make an adjustment in a subsequent sprint?

**Comment by angelcardoz** [comment]
@natalia-fitzgerald, we can release the way we have it, but would like to make the changes next sprint.

**Comment by natalia-fitzgerald** [comment]
Most up-to-date mock-ups can be found in Figma - Provide filing details step. 

**Default**
<img width="452" alt="Screenshot 2024-10-11 at 8 50 03 PM" src="https://github.com/user-attachments/assets/375b4eb2-b491-48a5-8df1-6e667a57bf2d">

**Error**
<img width="784" alt="Screenshot 2024-10-11 at 8 50 26 PM" src="https://github.com/user-attachments/assets/8cdd85ce-4b49-48e1-adfa-9bf818534390">

**Comment by natalia-fitzgerald** [comment]
**Updated after dev/design sync**
<img width="671" alt="Screenshot 2024-10-15 at 5 00 06 PM" src="https://github.com/user-attachments/assets/3e2dcafb-46c1-4a2b-8dfb-074b47cdae0a">

<img width="801" alt="Screenshot 2024-10-15 at 5 08 19 PM" src="https://github.com/user-attachments/assets/70c37f07-5fcd-49ff-847c-8de6bc8d8c03">
