### ISSUE TITLE
Typo on Beta Platform Home Page 

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/sbl-project#276]
<img width="397" alt="image" src="https://github.com/user-attachments/assets/71878b96-1ca4-41e3-a854-eb92471fd87f">
"The beta platform platform"

**Comment by billhimmelsbach** [comment]
Huh! I'll investigate this one @chynnakeys.

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
It looks like this has been updated on beta. Is this work completed?

**Comment by billhimmelsbach** [comment]
A weird git / deploy issue I found for this one, will have a release for this one soon.

**Comment by billhimmelsbach** [comment]
We'll be releasing this one after the bug bash next Thursday (November 7th 2024)

**Comment by billhimmelsbach** [comment]
This has been released on beta, so that it'd be ready for Angel's demo. 👍
