### ISSUE TITLE
[Story] Log out option when user profile is completed

### ISSUE THREAD

**Issue by angelcardoz** [cfpb/sbl-project#293]
### Epic

Epic issue includes overview, complete list of user stories, technical and content requirements, user testing task ideation, and current design mock-ups.

- <link to parent epic> 

### User story

- As a filer, I want an option to log out when I complete my user profile, so that I can ensure my account is secure after updating my information.

### Acceptance criteria

- Given  a user completed their user profile, when they click the "Submit" button and navigate to the confirmation page, then they should see a "log out" option and be able to log out of Keycloak and Login.gov.
- This behavior should be the same for a developer who has only removed only their institution association.

### Technical tasks

Team members should create technical tasks and add links (below) prior to sprint planning.

#### UX
- [x] Write initial user story
  - Review against task analysis for accuracy and relevance (if applicable)
  - Map story issue to the task analysis (if applicable)
- [ ] Validate user story with the team
  - Review for specificity and completeness

#### Content
- [ ] Add task

#### Front end
- [ ] Task (link)
- [ ] Task (link)

#### Back end
- [ ] Task (link)
- [ ] Task (link)

**Comment by natalia-fitzgerald** [comment]
@angelcardoz 
Can we update this story to include adding the Log out link on the Complete your user profile page itself. The idea here is that once a user logs in through Login.gov they would need a way to log out. So, the log out link should appear on both the Complete your user profile page and on the confirmation page.
