### ISSUE TITLE
[Task] Add a Paperwork Reduction Act notice

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/sbl-project#42]
As any visitor to the homepage, I want to understand my rights regarding the PRA.

### Acceptance criteria

- When I view the homepage, I should be able to see at a glance that I am protected by the PRA and I click a link to learn more.

### Depends on

- #29 

### Context

<img width="1034" alt="274596533-c23e2110-4412-49ce-86da-7c93755e19f6" src="https://github.com/cfpb/sbl-project/assets/19983248/929e68d6-de3d-43f1-8460-0adac55d554c">

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach
I think all work on this launched with beta. Can we go ahead and close this ticket?
