### ISSUE TITLE
[Task] Add a consent and notice advisory

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/sbl-project#43]
As any visitor to the homepage, I want to understand my rights when giving consent to use CFPB systems,

### Acceptance criteria

- When I view the homepage, I should be able to see at a glance how a CFPB system can be used.

### Depends on

- #29 

### Context
<img width="1466" alt="274596507-aec53af4-626d-4ca8-880a-82ab7529efac" src="https://github.com/cfpb/sbl-project/assets/19983248/4ae7cb22-d038-4cbf-8997-7f33ff70f7e9">

**Comment by natalia-fitzgerald** [comment]
@billhimmelsbach 
I think all work on this launched with beta. Can we go ahead and close this ticket?

**Comment by billhimmelsbach** [comment]
Sounds good @natalia-fitzgerald!
