### ISSUE TITLE
[Story] CFPB logo appears on Login.gov pages

### ISSUE THREAD

**Issue by cdorney25** [cfpb/sbl-project#64]
### User story

As a filer, I want to see the CFPB logo on the Login.gov page so that I know there is a connection between this external website and the CFPB process I am trying to complete. 

### Acceptance criteria

Given that a user follows the process of logging in to the filing platform, when they reach the Login.gov website and in every subsequent Login.gov page, then they will see the CFPB logo to the right of the Login.gov logo. 

![image](https://github.com/cfpb/sbl-project/assets/134086988/12483c31-7d6f-4dbc-948d-d0921bce9ce2)

### Depends on

- #9

### Technical tasks

- [ ] Add here
- [ ] Add here

### Context

Goal is to establish trust and a sense of security for the user as they navigate an external system and provide personal information

**Comment by angelcardoz** [comment]
@natalia-fitzgerald, this is minor, but do we want the CFPB logo background to be white or transparent? Currently, it's white. 
![image](https://github.com/cfpb/sbl-project/assets/148097357/45ed40cb-be05-4275-87c7-90fcaf3f12be)

**Comment by natalia-fitzgerald** [comment]
The CFPB logo should be transparent. I mentioned this to @billhimmelsbach a while back and he added it to a list here: https://github.com/cfpb/sbl-frontend/issues/209. Do we need to create a task for it?

**Comment by billhimmelsbach** [comment]
@natalia-fitzgerald Heyo! Can you add the transparent logo you want to use to this ticket?

**Comment by billhimmelsbach** [comment]
@natalia-fitzgerald Here are the guidelines for the logo:

https://developers.login.gov/user-experience/agency-logo/

**Comment by billhimmelsbach** [comment]
I went ahead and took a crack at it.
![Screenshot 2024-02-28 at 3 23 26 PM](https://github.com/cfpb/sbl-project/assets/19983248/f0cbfd3b-5f81-4f90-8458-c58fc3c6d02c)

using this logo:
![CFPB_logo](https://github.com/cfpb/sbl-project/assets/19983248/6bda465e-e7ed-4cb4-8e1c-90742f18eee6)

**Comment by billhimmelsbach** [comment]
Working well!
