### ISSUE TITLE
Establish a consistent approach to epics and build GH template

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-project#83]
The purpose of this issue is for the team to collaborate on a consistent approach to epic issues. Here's an example of what the template could look like.

---

**Milestone:** [Link to milestone]
Add a few sentences to describe the milestone.

# Epic: Epic name

### Overview
- List item
- List item

### Tasks
Use the following checklist to ensure each epic is built out properly. If needed, you can add or remove items.
- [ ] Pull together initial list of relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Post current wireframes and mock-ups
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### MVP (Beta release) 
- Story (link)
- Story (link)

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- List item
- List item

### Research goals
- Add here

### Task ideation 
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|

**Comment by dan-padgett** [comment]
@angelcardoz From our discussion this morning, for the User Testing section, can we add a subsection called "Research Goals" that goes above "Task Ideation"? So we'd have:
## User Testing
### Research goals
- Add here

### Task ideation
- Add here

**Comment by angelcardoz** [comment]
> @angelcardoz From our discussion this morning, for the User Testing section, can we add a subsection called "Research Goals" that goes above "Task Ideation"? So we'd have:
> 
> ## User Testing
> ### Research goals
> * Add here
> 
> ### Task ideation
> * Add here

Done. Thanks @dan-padgett. Updated our model above as well.
